/* eslint-disable react/jsx-props-no-spreading */
import React from 'react';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { ChakraProvider } from '@chakra-ui/react';

import Header from '../components/layout/Header';
import Main from '../components/layout/Main';
import '../styles/globals.css';

const MyApp = ({ Component, pageProps }: AppProps) => (
  <>
    <Head>
      <title>Nyanki</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <ChakraProvider>
      <Header />
      <Main>
        <Component {...pageProps} />
      </Main>
    </ChakraProvider>
  </>
);

export default MyApp;
